apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: awx-playbook-integrity-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: awx-playbook-integrity-manager-role
subjects:
- kind: ServiceAccount
  name: operator
  namespace: system
