---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: system
spec:
  template:
    spec:
      containers:
        - name: awx-playbook-integrity-manager
          env:
            - name: ANSIBLE_DEBUG_LOGS
              value: "TRUE"
